name: 'extractor action'
description: 'run the compile commands executor'
author: '@pseyfert'
branding:
  color: orange
  icon: list
inputs:
  demonstrator:
    description: "a meaningless string"
    required: true
    default: "rainbow"
runs:
  using: docker
  image: 'Dockerfile'
